CREATE TABLE `t_user_points` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'id',
  `m_user_id` int NOT NULL COMMENT 'ユーザーid',
  `t_project_id` int DEFAULT NULL COMMENT '物件id',
  `point_type_m_kv_id` int NOT NULL COMMENT 'ポイント区分',
  `point_grant_type_m_kv_id` int NOT NULL COMMENT 'ポイント付与区分、使用の場合0で固定',
  `changed_at` datetime NOT NULL COMMENT 'ポイント発生日',
  `point` int NOT NULL COMMENT 'ポイント数',
  `memo` varchar(1024) DEFAULT NULL COMMENT '備考',
  `created_m_user_id` int NOT NULL COMMENT '作成担当者',
  `updated_m_user_id` int NOT NULL COMMENT '更新担当者',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日',
  `deleted_at` datetime DEFAULT NULL COMMENT '削除日',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `fk_t_user_points_m_user_id_idx` (`m_user_id`) USING BTREE,
  KEY `fk_t_user_points_t_project_id_idx` (`t_project_id`) USING BTREE,
  KEY `id_t_user_points_point_date` (`changed_at`) USING BTREE,
  KEY `id_t_user_points_point_type_m_kv_id` (`point_type_m_kv_id`) USING BTREE,
  KEY `id_t_user_points_point_grant_type_m_kv_id` (`point_grant_type_m_kv_id`) USING BTREE,
  KEY `fk_t_user_points_created_m_user_id_idx` (`created_m_user_id`),
  KEY `fk_t_user_points_updated_m_user_id_idx` (`updated_m_user_id`),
  CONSTRAINT `fk_t_user_points_created_m_user_id` FOREIGN KEY (`created_m_user_id`) REFERENCES `m_users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_t_user_points_m_user_id` FOREIGN KEY (`m_user_id`) REFERENCES `m_users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_t_user_points_t_project_id` FOREIGN KEY (`t_project_id`) REFERENCES `t_projects` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_t_user_points_updated_m_user_id` FOREIGN KEY (`updated_m_user_id`) REFERENCES `m_users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=1328 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC COMMENT='ユーザーポイント';
