CREATE TABLE `t_project_points` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'id',
  `t_project_id` int NOT NULL COMMENT '物件id',
  `sales_per` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '営業ポイント率',
  `sales_point` int NOT NULL DEFAULT '0' COMMENT '営業ポイント',
  `prod_per` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '生産ポイント率',
  `prod_point` int NOT NULL DEFAULT '0' COMMENT '生産ポイント',
  `construct_coef` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '施工掛け率',
  `create_coef` decimal(5,2) NOT NULL DEFAULT '0.00' COMMENT '登録掛け率',
  `applicated_at` datetime DEFAULT NULL COMMENT '確定日',
  `closed_at` datetime DEFAULT NULL COMMENT '締め日',
  `created_m_user_id` int NOT NULL COMMENT '作成担当者',
  `updated_m_user_id` int NOT NULL COMMENT '更新担当者',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日',
  `deleted_at` datetime DEFAULT NULL COMMENT '削除日',
  PRIMARY KEY (`id`),
  KEY `fk_t_project_points_t_project_id_idx` (`t_project_id`),
  KEY `fk_t_project_points_created_m_user_id_idx` (`created_m_user_id`),
  KEY `fk_t_project_points_updated_m_user_id_idx` (`updated_m_user_id`),
  CONSTRAINT `fk_t_project_points_created_m_user_id` FOREIGN KEY (`created_m_user_id`) REFERENCES `m_users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_t_project_points_t_project_id` FOREIGN KEY (`t_project_id`) REFERENCES `t_projects` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_t_project_points_updated_m_user_id` FOREIGN KEY (`updated_m_user_id`) REFERENCES `m_users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=455 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='物件ポイント';
