import { DbRowAbstract } from "../../../../models/DbRowAbstract";
import { MMaterialDetail } from "../../../masters/class/models/MMaterialDetail";
/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export class TPOrderDetails extends DbRowAbstract {
  
  /** cd */
  cd: string | null = null;
  
  /** 作成日 */
  created_at?: Date | null = null;
  
  /** 削除日 */
  deleted_at: Date | null = null;
  
  /** 仕入日 */
  due_date: Date | null = null;
  
  /** id */
  id?: number;
  
  /** 材料明細id */
  m_material_detail_id: number | null = null;
  
  /** 材料名（銘柄のみ）仕入れで使用 */
  material_name: string | null = null;
  
  /** 材料サイズX */
  material_size_x: number | null = null;
  
  /** 材料サイズY */
  material_size_y: number | null = null;
  
  /** 社内備考 */
  memo: string | null = null;
  
  /** 品名・銘柄 */
  po_material_name: string | null = null;
  
  /** 単価 */
  price?: number;
  
  /** 仕入完了日 */
  purchase_completed_at: Date | null = null;
  
  /** 数量 */
  qty?: number;
  
  /** 発送先住所 */
  shipping_address: string | null = null;
  
  /** 明細備考 */
  slip_memo: string | null = null;
  
  /** 発注id */
  t_p_order_id: number = 0 ;
  
  /** 't_project_construction_users紐づけid */
  t_project_construction_user_id: number | null = null;
  
  /** 物件id */
  t_project_id: number | null = null;
  
  /** 物件商品工程id */
  t_project_product_process_id: number | null = null;
  
  /** 金額 */
  total_price?: number;
  
  /** 単位 */
  unit_m_kv_id: number | null = null;
  
  /** 更新日 */
  updated_at?: Date | null = null;

  t_p_order?:any

  m_material_detail?:MMaterialDetail
  
  public static parse(obj:Partial<TPOrderDetails>){
      const row = new TPOrderDetails(obj.created_m_user_id ?? 0 ) ;  
      Object.assign(row, obj);
      return row ; 
  }

  public static is(arg:any):arg is TPOrderDetails { 
      if ( arg?.TPOrderDetails === undefined) return false ; 
      return arg.TPOrderDetails ; 
  } 
}


