CREATE TABLE `sm_user_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key_m_kv_id` INT NOT NULL COMMENT 'キーカテゴリ',
  `order_no` INT NULL DEFAULT NULL COMMENT '表示順',
  `name` VARCHAR(1024) NULL DEFAULT NULL COMMENT '設定名称',
  `application` VARCHAR(1024) NULL DEFAULT NULL COMMENT '適用',
  `default_value` VARCHAR(1024) NULL DEFAULT NULL COMMENT '設定デフォルト値',
  `option_01` VARCHAR(1024) NULL DEFAULT NULL COMMENT '汎用カラム01',
  `option_02` VARCHAR(1024) NULL DEFAULT NULL COMMENT '汎用カラム02',
  `option_03` VARCHAR(1024) NULL DEFAULT NULL COMMENT '汎用カラム03',
  `option_04` VARCHAR(1024) NULL DEFAULT NULL COMMENT '汎用カラム04',
  `option_05` VARCHAR(1024) NULL DEFAULT NULL COMMENT '汎用カラム05',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日',
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新日',
  PRIMARY KEY (`id`))
COMMENT = '個別設定';
